# Password for the 'elastic' user (at least 6 characters) elastic 用户名的密码
ELASTIC_PASSWORD=7j1TEQyVyoVLJ5G4SXM3NcH6Z

# Password for the 'kibana_system' user (at least 6 characters) kibana 密码
KIBANA_PASSWORD=ZFzBxCF1Hrz5Gp5UAElBLnNFS

# Version of Elastic products
STACK_VERSION=8.7.0

# Set the cluster name
CLUSTER_NAME=docker-cluster

# Set to 'basic' or 'trial' to automatically start the 30-day trial
LICENSE=basic
#LICENSE=trial

# Port to expose Elasticsearch HTTP API to the host
ES_PORT=9200
#ES_PORT=127.0.0.1:9200
# 集群间内部通讯
TRANSPORT_PORT=9300

# Port to expose Kibana to the host
KIBANA_PORT=5601
#KIBANA_PORT=80

# Increase or decrease based on the available host memory (in bytes)
MEM_LIMIT=1073741824

# Project namespace (defaults to the current folder name if not set)
#项目命名空间 (如果未设置，默认为当前文件夹名称)
#COMPOSE_PROJECT_NAME=my-es
